name: 'Push Docker Images'

on:
  push:
    branches: [v4]
  workflow_dispatch:

jobs:
  push-amd64:
    name: 'push (amd64)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get commit sha
        id: sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          tags: |
            ghcr.io/diced/zipline:v4-amd64
            ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-amd64

  push-arm64:
    name: 'push (arm64)'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Get commit sha
        id: sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          tags: |
            ghcr.io/diced/zipline:v4-arm64
            ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-arm64

  ammend-builds:
    runs-on: ubuntu-latest
    needs: [push-amd64, push-arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Get commit sha
        id: sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull images
        run: |
          docker pull --platform=linux/amd64 ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-amd64
          docker pull --platform=linux/arm64 ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-arm64

      - name: create manifests
        run: |
          docker manifest create ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }} \
            --amend ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-amd64 \
            --amend ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-arm64 && \
          docker manifest create ghcr.io/diced/zipline:v4 \
            --amend ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-amd64 \
            --amend ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }}-arm64

      - name: push manifests
        run: |
          docker manifest push ghcr.io/diced/zipline:v4-${{ steps.sha.outputs.short_sha }} && \
          docker manifest push ghcr.io/diced/zipline:v4
